<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1OQPK0U" failures="1" tests="6" name="This is Test Case" time="0.207" errors="0" timestamp="2020-11-14T10:49:54 IST">
  <testcase classname="TestNGTutorial.Annotations" name="Test1" time="0.006"/>
  <testcase classname="TestNGTutorial.Annotations" name="Test2" time="0.001"/>
  <testcase classname="TestNGTutorial.Annotations" name="Test3" time="0.001"/>
  <testcase classname="TestNGTutorial.Annotations" name="Test4" time="0.001"/>
  <testcase classname="TestNGTutorial.Assertion" name="Test1" time="0.051">
    <failure type="java.lang.AssertionError" message="test case is passed expected [abcw] but found [abc]">
      <![CDATA[java.lang.AssertionError: test case is passed expected [abcw] but found [abc]
at TestNGTutorial.Assertion.Test1(Assertion.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="TestNGTutorial.Assertion" name="Test2" time="0.002"/>
</testsuite> <!-- This is Test Case -->
